/**
 * Human-reviewed UI and editorial copy for the public site.
 *
 * Vietnamese is the source language. Every alternate locale is written for a
 * B2B export audience rather than generated word-for-word from Vietnamese.
 */
export const SITE_UI_COPY = {
  vi: {
    skip: "Đến nội dung chính",
    nav: { home: "Trang chủ", about: "Về chúng tôi", journey: "Hành trình", products: "Sản phẩm", partners: "Đối tác", journal: "Tin tức", contact: "Liên hệ" },
    exportCatalog: "Danh mục xuất khẩu",
    language: "Chọn ngôn ngữ",
    openMenu: "Mở menu",
    closeMenu: "Đóng menu",
    primaryNavigation: "Điều hướng chính",
    mobileMenuTitle: "Điều hướng",
    productNavigation: "Sản phẩm và kết nối",
    brand: {
      topbar: "Manufacturing with Heart, Trading with Vision",
      mobileDescription: "Khám phá Hồng Tâm Rosic Global",
      logoAlt: "Biểu trưng Hồng Tâm Rosic Global",
      homeLabel: "Hồng Tâm Rosic Global, trang chủ",
    },
    theme: { switchToDark: "Chuyển sang giao diện tối", switchToLight: "Chuyển sang giao diện sáng", light: "Sáng", dark: "Tối" },
    hero: { eyebrow: "TỪ TÂM VIỆT, VƯƠN TẦM THẾ GIỚI", start: "Tinh hoa từ đất.", accent: "Trao gửi bằng tâm.", first: "Kết nối nông sản Việt với thế giới.", second: "Chăm chút từng mùa vụ, vun đắp những mối quan hệ bền lâu.", cta: "Khám phá danh mục xuất khẩu", origin: "Nông sản Việt Nam", caption: "Gieo giá trị. Gặt niềm tin." },
    marquee: ["Trái cây tươi", "Rau củ theo mùa", "Hạt & ngũ cốc", "Nông sản chế biến"],
    marqueeLabel: "Các nhóm nông sản",
    marqueeHelp: "Chạm hoặc nhấn Enter để dừng hay tiếp tục chuyển động.",
    about: {
      alt: "Xoài, thanh long ruột đỏ, dưa lưới, bơ, hạt điều và cà phê trên nền sáng",
      eyebrow: "CÂU CHUYỆN HỒNG TÂM",
      title: ["Gốc rễ Việt Nam.", "Tầm nhìn toàn cầu."],
      first: "Chúng tôi tin rằng giá trị của nông sản bắt đầu từ sự tận tâm với đất, với người trồng và với từng sản phẩm.",
      second: "Hồng Tâm Rosic Global kết nối nguồn nông sản Việt với nhu cầu của đối tác trong nước và quốc tế. Mỗi cuộc hợp tác bắt đầu bằng việc hiểu đúng nhu cầu, trao đổi rõ ràng và cùng xây dựng một hướng đi lâu dài.",
      link: "Khám phá hành trình của chúng tôi",
      values: [
        { title: "Từ nguồn trồng", body: "Quan tâm đến xuất xứ." },
        { title: "Đến từng sản phẩm", body: "Chăm chút khâu lựa chọn." },
        { title: "Qua mỗi kết nối", body: "Hướng đến hợp tác dài lâu." },
      ],
    },
    catalog: { eyebrow: "TỪ THIÊN NHIÊN VIỆT NAM", title: "Mỗi mùa, một thức quà.", body: "Khám phá danh mục nông sản và cùng chúng tôi lựa chọn sản phẩm phù hợp với nhu cầu của bạn.", filter: "Lọc nhóm sản phẩm", search: "Tìm sản phẩm", detail: "Xem chi tiết", viewProduct: (title) => `Xem ${title}`, resultCount: (count) => `${count} sản phẩm`, noResultTitle: "Chưa tìm thấy sản phẩm phù hợp", noResultBody: "Thử tên ngắn hơn hoặc xem lại toàn bộ danh mục.", reset: "Xem tất cả sản phẩm", note: "Danh mục giới thiệu. Mùa vụ, quy cách và khả năng cung ứng được xác nhận khi trao đổi đơn hàng." },
    tabs: { all: "Tất cả", fruit: "Trái cây tươi", vegetables: "Rau củ theo mùa", nuts: "Hạt & ngũ cốc", processed: "Nông sản chế biến" },
    journey: {
      title: ["Một hành trình.", "Vẹn nguyên sự tận tâm."],
      lead: "Từ lựa chọn nguồn hàng đến trao gửi sản phẩm, mỗi bước đều cần sự thấu hiểu và phối hợp.",
      label: "Các bước trong hành trình",
      steps: [
        { title: "Bắt đầu từ nguồn trồng", description: "Hiểu xuất xứ và nhịp mùa vụ để có cơ sở lựa chọn sản phẩm phù hợp với nhu cầu.", alt: "Những đồi chè xanh trải dài trong ánh nắng", caption: "Từ đất lành, câu chuyện bắt đầu." },
        { title: "Lựa chọn từng sản phẩm", description: "Trao đổi về chủng loại, độ chín, kích cỡ và những đặc điểm quan trọng với mỗi đơn hàng.", alt: "Các loại trái cây, hạt điều và cà phê được bày trên nền sáng", caption: "Mỗi nhu cầu, một lựa chọn riêng." },
        { title: "Chăm chút cách đóng gói", description: "Thống nhất cách sơ chế, quy cách bao bì và điều kiện bảo quản theo từng loại nông sản.", alt: "Dây chuyền phân loại và đóng gói nông sản trong không gian sáng", caption: "Hiểu sản phẩm để chăm chút đúng cách." },
        { title: "Kết nối đến nơi nhận", description: "Làm rõ lịch giao, điểm nhận và trách nhiệm của các bên để việc phối hợp được thuận lợi.", alt: "Không gian nhà kho và khu vực tập kết hàng hóa", caption: "Phối hợp rõ ràng trên từng chặng." },
      ],
    },
    partners: {
      title: ["Đi xa hơn,", "khi đi cùng nhau."],
      lead: "Từ nhà phân phối, đơn vị bán lẻ đến đối tác nhập khẩu, chúng tôi luôn trân trọng những kết nối cùng chung giá trị.",
      link: "Trao đổi cơ hội hợp tác",
      types: ["Nhà phân phối", "Bán lẻ & thực phẩm", "Đối tác nhập khẩu", "Đơn vị sản xuất"],
      qualityTitle: "Rõ ràng ngay từ đầu",
      qualityBody: "Xuất xứ, quy cách, hồ sơ chất lượng và điều kiện giao hàng cần được đối chiếu cho từng sản phẩm và từng đơn hàng.",
    },
    journal: {
      title: "Chuyện từ những mùa xanh.",
      lead: "Những góc nhìn về sản phẩm, nguồn trồng và cách bắt đầu một cuộc hợp tác.",
      read: "Đọc câu chuyện",
      minutes: (count) => `${count} phút đọc`,
      articles: {
        "chon-nong-san-theo-mua": { title: "Chọn đúng mùa, hiểu đúng sản phẩm.", category: "Câu chuyện mùa vụ", alt: "Đồi chè xanh trong ánh nắng tự nhiên", excerpt: "Một danh mục nông sản phù hợp bắt đầu từ việc hiểu nhu cầu sử dụng và những thay đổi của mùa vụ.", sections: [{ title: "Bắt đầu từ nơi sản phẩm sẽ đến", body: "Sản phẩm dùng cho bán lẻ, bếp ăn hay chế biến sẽ có những yêu cầu khác nhau. Hãy ghi lại mục đích sử dụng, thời điểm cần hàng và các đặc điểm bạn ưu tiên, chẳng hạn kích cỡ, độ chín hoặc hình thức bên ngoài." }, { title: "Trao đổi về mùa vụ và khả năng thay thế", body: "Thời điểm thu hoạch và nguồn hàng có thể thay đổi theo vùng trồng. Khi lên kế hoạch, hãy hỏi về giai đoạn có hàng, khả năng cung ứng dự kiến và lựa chọn thay thế nếu sản phẩm bạn cần chưa phù hợp vào thời điểm đó." }, { title: "Xác nhận thông tin của lô hàng", body: "Tên gọi chung và ảnh giới thiệu chưa thể hiện mọi đặc điểm của một lô nông sản. Trước khi đặt hàng, hai bên nên thống nhất mô tả sản phẩm, xuất xứ, quy cách và cách đánh giá khi nhận hàng; có thể trao đổi mẫu khi cần." }] },
        "dong-goi-va-van-chuyen": { title: "Một hành trình tốt cần cách gói phù hợp.", category: "Góc nhìn sản phẩm", alt: "Dây chuyền phân loại và đóng gói nông sản trong không gian sáng", excerpt: "Bao bì và kế hoạch giao nhận là những chi tiết nên được trao đổi cùng sản phẩm ngay từ đầu.", sections: [{ title: "Bao bì bắt đầu từ đặc tính sản phẩm", body: "Trái cây, rau lá và hạt khô có những đặc điểm khác nhau. Thay vì chỉ chọn một kích cỡ thùng, hãy trao đổi về vật liệu, khối lượng mỗi đơn vị, cách sắp xếp và yêu cầu bảo quản của sản phẩm cụ thể." }, { title: "Nhìn vào toàn bộ chặng đường", body: "Thời gian từ lúc chuẩn bị hàng đến khi sử dụng là thông tin cần thiết để bàn về đóng gói. Hai bên nên làm rõ phương thức vận chuyển, các điểm trung chuyển, lịch nhận hàng và điều kiện bảo quản ở nơi nhận." }, { title: "Thống nhất cách nhận và kiểm tra", body: "Quy cách nhãn, số lượng kiện và thông tin lô hàng giúp việc đối chiếu thuận tiện hơn. Hãy thống nhất trước người nhận, cách kiểm tra, thời điểm phản hồi và đầu mối xử lý nếu có điểm cần làm rõ khi giao hàng." }] },
        "bat-dau-don-hang-b2b": { title: "Đơn hàng đầu tiên bắt đầu bằng sự rõ ràng.", category: "Kết nối đối tác", alt: "Danh mục trái cây, hạt điều và cà phê được sắp xếp cùng nhau", excerpt: "Một bản yêu cầu ngắn gọn nhưng đủ thông tin giúp cuộc trao đổi giữa các đối tác đi vào đúng nhu cầu.", sections: [{ title: "Mô tả điều bạn đang tìm kiếm", body: "Hãy bắt đầu bằng tên sản phẩm, mục đích sử dụng và khối lượng dự kiến. Nếu đã có yêu cầu về kích cỡ, cách chế biến hoặc bao bì, bạn nên ghi rõ; nếu chưa, hãy nêu những điểm cần được tư vấn thêm." }, { title: "Cung cấp thời gian và nơi nhận", body: "Thời điểm cần hàng, địa điểm nhận và tần suất mua dự kiến giúp hai bên trao đổi sát thực tế hơn. Với đơn hàng quốc tế, hãy nêu thị trường đích và những hồ sơ mà phía nhận hàng yêu cầu để cùng đối chiếu." }, { title: "Chốt lại nội dung đã thống nhất", body: "Trước khi xác nhận đơn hàng, hãy đối chiếu sản phẩm, số lượng, giá, quy cách, lịch giao và các điều kiện đã trao đổi. Một bản tổng hợp rõ ràng giúp mỗi bên biết mình cần chuẩn bị gì cho bước tiếp theo." }] },
      },
    },
    footer: { tagline: ["Gieo giá trị từ tâm.", "Kết nối những mùa xanh."], explore: "Khám phá", products: "Sản phẩm", invitation: "Bắt đầu một kết nối tốt đẹp.", greeting: "Chào Hồng Tâm", social: "Kết nối nhanh", privacy: "Thông tin & quyền riêng tư", backTop: "Về đầu trang" },
    dialog: {
      close: "Đóng chi tiết", articleCta: "Cùng trao đổi thêm", productGroup: "Nhóm sản phẩm", format: "Quy cách", formatValue: "Trao đổi theo nhu cầu", imageNote: "Hình ảnh minh họa sản phẩm. Xuất xứ, mùa vụ và thông số được xác nhận theo lô hàng.", request: "Yêu cầu sản phẩm này", policyTitle: "Thông tin & quyền riêng tư", policyLead: "Cách chúng tôi sử dụng nội dung trên website và thông tin trong yêu cầu báo giá.",
      policySections: [
        { title: "Thông tin sản phẩm", body: "Danh mục và ảnh được dùng để giới thiệu nhóm sản phẩm. Một số hình ảnh minh họa được tạo bằng công cụ AI. Ảnh không xác nhận một vùng trồng hay cơ sở thuộc sở hữu doanh nghiệp. Thông số, nguồn gốc, hồ sơ chất lượng và khả năng cung ứng cần được xác nhận khi trao đổi." },
        { title: "Yêu cầu báo giá", body: "Khi bạn gửi biểu mẫu, thông tin được chuyển tới hệ thống báo giá để phân luồng cho đội ngũ Kinh doanh và gửi email xác nhận. Số WhatsApp chỉ được dùng để gửi tin nhắn xác nhận khi bạn chủ động đồng ý; nếu không chọn đồng ý, chúng tôi không gửi tin qua WhatsApp." },
        { title: "Nội dung tham khảo", body: "Các bài viết là nội dung giới thiệu và hướng dẫn trao đổi đơn hàng; không phải hồ sơ chứng nhận hoặc thông báo kết quả kinh doanh." },
      ],
    },
  },
  en: {
    skip: "Skip to main content",
    nav: { home: "Home", about: "About us", journey: "Our approach", products: "Products", partners: "Partners", journal: "Insights", contact: "Contact" },
    exportCatalog: "Export catalogue", language: "Choose language", openMenu: "Open menu", closeMenu: "Close menu", primaryNavigation: "Primary navigation", mobileMenuTitle: "Navigation", productNavigation: "Products and contact",
    brand: { topbar: "Manufacturing with Heart, Trading with Vision", mobileDescription: "Explore Hồng Tâm Rosic Global", logoAlt: "Hồng Tâm Rosic Global logo", homeLabel: "Hồng Tâm Rosic Global, home" },
    theme: { switchToDark: "Switch to dark mode", switchToLight: "Switch to light mode", light: "Light", dark: "Dark" },
    hero: { eyebrow: "ROOTED IN VIETNAM. READY FOR THE WORLD.", start: "Grown with care.", accent: "Delivered with purpose.", first: "We bring Vietnamese agricultural products to partners around the world.", second: "Caring for every harvest and building partnerships that last.", cta: "Explore the export catalogue", origin: "Vietnam-grown produce", caption: "Cultivate value. Build trust." },
    marquee: ["Fresh fruit", "Seasonal vegetables", "Nuts & grains", "Processed agricultural products"], marqueeLabel: "Agricultural product categories", marqueeHelp: "Tap or press Enter to pause or resume the moving rail.",
    about: { alt: "Mango, red dragon fruit, cantaloupe, avocado, cashews and coffee against a light background", eyebrow: "THE HỒNG TÂM STORY", title: ["Vietnamese roots.", "A global outlook."], first: "We believe agricultural value begins with care: for the land, the growers and every product.", second: "Hồng Tâm Rosic Global connects Vietnamese supply with the needs of partners at home and abroad. Every partnership starts with clear requirements, candid communication and a shared long-term direction.", link: "Discover our approach", values: [{ title: "At the growing source", body: "Origin matters." }, { title: "In every product", body: "Selection is handled with care." }, { title: "In every partnership", body: "Built for the long term." }] },
    catalog: { eyebrow: "FROM VIETNAM'S GROWING REGIONS", title: "Something worth sharing in every season.", body: "Browse our agricultural range and find the product that fits your requirement.", filter: "Filter product groups", search: "Search products", detail: "View details", viewProduct: (title) => `View ${title}`, resultCount: (count) => `${count} products`, noResultTitle: "No matching product found", noResultBody: "Try a shorter search term or return to the full catalogue.", reset: "View all products", note: "This catalogue is an introduction. Seasonality, packing and availability are confirmed for each enquiry." },
    tabs: { all: "All", fruit: "Fresh fruit", vegetables: "Seasonal vegetables", nuts: "Nuts & grains", processed: "Processed agricultural products" },
    journey: { title: ["One journey.", "Care at every step."], lead: "From sourcing to delivery, every stage calls for mutual understanding and close coordination.", label: "Steps in our approach", steps: [{ title: "Start at the source", description: "Understand origin and seasonality before choosing the product that fits the brief.", alt: "Sunlit green tea hills", caption: "Every story begins with good soil." }, { title: "Select with intent", description: "Align on variety, maturity, size and the details that matter to each order.", alt: "Fruit, cashews and coffee arranged against a light background", caption: "A considered choice for every brief." }, { title: "Pack with care", description: "Agree preparation, packing and storage conditions for each agricultural product.", alt: "A bright agricultural sorting and packing line", caption: "Know the product, then prepare it well." }, { title: "Connect to destination", description: "Clarify delivery timing, destination and responsibilities so each handover runs smoothly.", alt: "A warehouse and goods consolidation area", caption: "Clear coordination at every stage." }] },
    partners: { title: ["Go further", "together."], lead: "From distributors and retailers to import partners, we value relationships built around shared standards.", link: "Discuss a partnership", types: ["Distributors", "Retail & food service", "Import partners", "Manufacturers"], qualityTitle: "Clear from the outset", qualityBody: "Origin, specification, quality documentation and delivery terms should be reviewed for every product and every order." },
    journal: { title: "Notes from the growing seasons.", lead: "Practical perspectives on products, sourcing and beginning a productive partnership.", read: "Read the story", minutes: (count) => `${count} min read`, articles: {
      "chon-nong-san-theo-mua": { title: "Choose the right season. Understand the product.", category: "Seasonal sourcing", alt: "Green tea hills in natural sunlight", excerpt: "A well-matched agricultural range begins with the intended use and the realities of the season.", sections: [{ title: "Begin with the destination", body: "Retail, food service and manufacturing each call for different product choices. Set out the intended use, required timing and priorities such as size, maturity or presentation." }, { title: "Discuss seasonality and alternatives", body: "Harvest timing and supply can vary by growing region. When planning, ask about the current availability window, expected supply and suitable alternatives if a product is not in season." }, { title: "Confirm the lot", body: "A generic product name and introductory photo do not describe every lot. Before ordering, agree the product description, origin, packing and receiving checks; review a sample when it is needed." }] },
      "dong-goi-va-van-chuyen": { title: "Good journeys begin with the right packing.", category: "Product perspective", alt: "A bright agricultural sorting and packing line", excerpt: "Packing and delivery planning are details best agreed alongside the product from the start.", sections: [{ title: "Packing follows the product", body: "Fresh fruit, leafy vegetables and dry goods have different needs. Instead of choosing a carton size in isolation, align materials, unit weight, arrangement and storage requirements for the specific product." }, { title: "Consider the whole route", body: "The time between packing and use informs the packing decision. Clarify the transport method, handover points, receiving schedule and storage conditions at destination." }, { title: "Agree receiving and checks", body: "Labels, pack counts and lot information make reconciliation easier. Agree the receiver, inspection method, response timing and escalation contact before delivery." }] },
      "bat-dau-don-hang-b2b": { title: "A first B2B order begins with clarity.", category: "Partner connection", alt: "A selection of fruit, cashews and coffee arranged together", excerpt: "A concise, complete enquiry gives both teams a practical starting point for a useful conversation.", sections: [{ title: "Describe what you need", body: "Start with product, intended use and indicative volume. State any requirements for size, processing or packing; if those are still open, identify the areas where you would welcome guidance." }, { title: "Share timing and destination", body: "Needed-by date, delivery point and expected buying frequency help make the discussion practical. For international orders, include the target market and the documentation required at destination." }, { title: "Confirm what has been agreed", body: "Before confirming an order, reconcile product, quantity, price, specification, delivery schedule and terms. A clear summary lets each side prepare the next step." }] },
    } },
    footer: { tagline: ["Value, grown with care.", "Partnerships, built to last."], explore: "Explore", products: "Products", invitation: "Let’s start a conversation.", greeting: "Talk to Hồng Tâm", social: "Quick links", privacy: "Information & privacy", backTop: "Back to top" },
    dialog: { close: "Close details", articleCta: "Continue the conversation", productGroup: "Product group", format: "Format", formatValue: "Agreed around your requirement", imageNote: "Illustrative product image. Origin, season and specifications are confirmed for each lot.", request: "Request this product", policyTitle: "Information & privacy", policyLead: "How this website uses its content and the details included in quotation requests.", policySections: [{ title: "Product information", body: "The catalogue and imagery introduce product groups. Some illustrative images are AI-generated and do not verify a growing region or a facility owned by the company. Origin, quality documentation, specifications and availability must be confirmed during the enquiry." }, { title: "Quotation requests", body: "When you submit the form, your details are sent to our quotation system for sales routing and an email confirmation. We use a WhatsApp number for a confirmation message only when you explicitly opt in; if you do not opt in, no WhatsApp message is sent." }, { title: "Reference content", body: "Articles provide introductory guidance for commercial conversations. They are not certificates or business-performance statements." }] },
  },
  zh: {
    skip: "跳至主要内容", nav: { home: "首页", about: "关于我们", journey: "合作流程", products: "产品", partners: "合作伙伴", journal: "行业洞见", contact: "联系我们" }, exportCatalog: "出口产品目录", language: "选择语言", openMenu: "打开菜单", closeMenu: "关闭菜单", primaryNavigation: "主导航", mobileMenuTitle: "导航", productNavigation: "产品与联系",
    brand: { topbar: "用心制造，远见贸易", mobileDescription: "了解 Hồng Tâm Rosic Global", logoAlt: "Hồng Tâm Rosic Global 标志", homeLabel: "Hồng Tâm Rosic Global 首页" },
    theme: { switchToDark: "切换为深色模式", switchToLight: "切换为浅色模式", light: "浅色", dark: "深色" },
    hero: { eyebrow: "源自越南，连接世界", start: "大地孕育的精华。", accent: "以真心传递。", first: "让优质越南农产品走向全球合作伙伴。", second: "珍视每一季收成，建立长久可靠的合作。", cta: "浏览出口产品目录", origin: "越南农产品", caption: "培育价值，赢得信任。" }, marquee: ["新鲜水果", "时令蔬菜", "坚果与谷物", "加工农产品"], marqueeLabel: "农产品类别", marqueeHelp: "轻触或按 Enter 键可暂停或继续滚动。",
    about: { alt: "浅色背景上的芒果、红心火龙果、网纹瓜、牛油果、腰果和咖啡", eyebrow: "HỒNG TÂM 的故事", title: ["扎根越南。", "放眼全球。"], first: "我们相信，农产品的价值源于对土地、种植者和每一件产品的用心。", second: "Hồng Tâm Rosic Global 将越南的产地供应与国内外合作伙伴的需求相连。每一次合作都从明确需求、坦诚沟通和共同规划长期方向开始。", link: "了解我们的合作流程", values: [{ title: "从产地开始", body: "重视原产地。" }, { title: "到每件产品", body: "用心甄选。" }, { title: "贯穿每次合作", body: "着眼长期共赢。" }] },
    catalog: { eyebrow: "来自越南产区", title: "每个季节，都有值得分享的风味。", body: "浏览我们的农产品系列，为您的需求找到合适选择。", filter: "筛选产品类别", search: "搜索产品", detail: "查看详情", viewProduct: (title) => `查看 ${title}`, resultCount: (count) => `${count} 款产品`, noResultTitle: "未找到匹配产品", noResultBody: "请尝试更短的关键词，或返回完整目录。", reset: "查看全部产品", note: "本目录用于介绍。季节、包装和供货情况以每次询盘确认为准。" }, tabs: { all: "全部", fruit: "新鲜水果", vegetables: "时令蔬菜", nuts: "坚果与谷物", processed: "加工农产品" },
    journey: { title: ["一段合作旅程。", "每一步都用心。"], lead: "从选择货源到交付产品，每一步都离不开相互理解和紧密配合。", label: "合作流程步骤", steps: [{ title: "从产地开始", description: "先了解原产地和产季，再选择符合需求的产品。", alt: "阳光下连绵起伏的绿色茶山", caption: "好土地，孕育好故事。" }, { title: "细心甄选产品", description: "确认品种、成熟度、尺寸以及每个订单关注的细节。", alt: "浅色背景上陈列的水果、腰果和咖啡", caption: "每一项需求，都有合适选择。" }, { title: "用心规划包装", description: "根据不同农产品确认预处理、包装规格和储存条件。", alt: "明亮环境中的农产品分选与包装线", caption: "了解产品，才能妥善准备。" }, { title: "顺利送达目的地", description: "明确交付时间、收货地点和双方责任，让每一次衔接更顺畅。", alt: "仓库和货物集散区域", caption: "每一段路，都清楚协同。" }] },
    partners: { title: ["携手同行，", "走得更远。"], lead: "无论是经销商、零售商还是进口合作伙伴，我们珍视建立在共同标准之上的每一份连接。", link: "洽谈合作机会", types: ["经销商", "零售与餐饮", "进口合作伙伴", "生产企业"], qualityTitle: "从一开始就清晰", qualityBody: "每一项产品和每一笔订单，都应核对原产地、规格、质量文件和交付条件。" },
    journal: { title: "来自丰收季的分享。", lead: "关于产品、产地和开启高效合作的实用见解。", read: "阅读文章", minutes: (count) => `${count} 分钟阅读`, articles: {
      "chon-nong-san-theo-mua": { title: "选对产季，读懂产品。", category: "产季洞见", alt: "自然阳光下的绿色茶山", excerpt: "合适的农产品组合，始于对使用场景和季节变化的理解。", sections: [{ title: "先看产品将抵达哪里", body: "零售、餐饮和加工对产品的要求各不相同。请明确使用场景、所需时间，以及尺寸、成熟度或外观等优先事项。" }, { title: "沟通产季与替代方案", body: "收获时间和供货情况会因产区而异。规划时，可了解当前供货窗口、预计供应量，以及产品不在合适产季时的替代选择。" }, { title: "确认批次信息", body: "通用名称和介绍图片并不能呈现每个批次的全部特点。下单前，双方应确认产品描述、原产地、包装和收货检验方式；必要时可先确认样品。" }] },
      "dong-goi-va-van-chuyen": { title: "好的旅程，始于合适的包装。", category: "产品视角", alt: "明亮环境中的农产品分选与包装线", excerpt: "包装与交付计划，最好从一开始就与产品本身一同确认。", sections: [{ title: "包装要匹配产品特性", body: "水果、叶菜和干货的需求各不相同。除了箱型，还应确认材料、单件重量、摆放方式和具体产品的储存要求。" }, { title: "看完整条运输路径", body: "从备货到使用的时间会影响包装方案。双方应明确运输方式、中转节点、收货时间和目的地的储存条件。" }, { title: "确认收货与检验方式", body: "标签、包装数量和批次信息能让核对更顺畅。交货前应确认收货人、检验方式、反馈时限和需要澄清时的联系人。" }] },
      "bat-dau-don-hang-b2b": { title: "第一笔 B2B 订单，从清晰沟通开始。", category: "合作连接", alt: "陈列在一起的水果、腰果和咖啡", excerpt: "一份简洁而完整的询盘，能让双方团队从真正的需求出发开展沟通。", sections: [{ title: "描述您的需求", body: "先说明产品、使用场景和预估数量。如对尺寸、加工或包装已有要求，请明确提出；如仍待确认，也请说明希望获得建议的部分。" }, { title: "提供时间与目的地", body: "所需到货时间、收货地点和预计采购频率，能让沟通更贴近实际。国际订单请提供目标市场及目的地要求的文件。" }, { title: "确认已达成的共识", body: "确认订单前，请核对产品、数量、价格、规格、交付计划和已沟通的条件。一份清晰的汇总能帮助双方准备下一步。" }] },
    } },
    footer: { tagline: ["用心培育价值。", "让合作历久弥新。"], explore: "探索", products: "产品", invitation: "让我们开始交流。", greeting: "联系 Hồng Tâm", social: "快捷链接", privacy: "信息与隐私", backTop: "返回顶部" },
    dialog: { close: "关闭详情", articleCta: "继续交流", productGroup: "产品类别", format: "产品形式", formatValue: "根据您的需求沟通确认", imageNote: "产品图片仅供展示。原产地、产季和规格以每个批次的确认结果为准。", request: "咨询此产品", policyTitle: "信息与隐私", policyLead: "网站内容及报价请求信息的使用方式。", policySections: [{ title: "产品信息", body: "目录和图片用于介绍产品类别。部分展示图片由 AI 工具生成，并不证明某个种植区域或企业自有设施。原产地、质量文件、规格和供货情况须在询盘时确认。" }, { title: "报价请求", body: "提交表单后，信息将发送至报价系统，用于分配给销售团队并发送邮件确认。只有在您明确同意时，我们才会通过 WhatsApp 号码发送确认消息；未选择同意时，不会发送 WhatsApp 消息。" }, { title: "参考内容", body: "文章提供商业沟通的介绍性建议，并非认证文件或经营业绩说明。" }] },
  },
  ko: {
    skip: "본문으로 건너뛰기", nav: { home: "홈", about: "회사 소개", journey: "협업 과정", products: "제품", partners: "파트너", journal: "인사이트", contact: "문의" }, exportCatalog: "수출 카탈로그", language: "언어 선택", openMenu: "메뉴 열기", closeMenu: "메뉴 닫기", primaryNavigation: "주요 메뉴", mobileMenuTitle: "메뉴", productNavigation: "제품 및 문의",
    brand: { topbar: "정성으로 만들고, 비전으로 거래합니다", mobileDescription: "Hồng Tâm Rosic Global 살펴보기", logoAlt: "Hồng Tâm Rosic Global 로고", homeLabel: "Hồng Tâm Rosic Global 홈" },
    theme: { switchToDark: "다크 모드로 전환", switchToLight: "라이트 모드로 전환", light: "라이트", dark: "다크" },
    hero: { eyebrow: "베트남의 정성을 세계로", start: "대지에서 온 정성.", accent: "마음으로 전합니다.", first: "베트남의 좋은 농산물을 세계의 파트너와 잇습니다.", second: "매 계절의 수확을 세심하게 돌보고 오래가는 협업을 만들어 갑니다.", cta: "수출 카탈로그 보기", origin: "베트남 농산물", caption: "가치를 키우고 신뢰를 쌓습니다." }, marquee: ["신선 과일", "제철 채소", "견과류와 곡물", "가공 농산물"], marqueeLabel: "농산물 카테고리", marqueeHelp: "탭하거나 Enter 키를 눌러 움직임을 멈추거나 다시 시작하세요.",
    about: { alt: "밝은 배경에 놓인 망고, 레드 드래곤프루트, 멜론, 아보카도, 캐슈넛, 커피", eyebrow: "HỒNG TÂM 이야기", title: ["베트남에 뿌리내리고,", "세계로 시선을 넓힙니다."], first: "농산물의 가치는 토지와 재배자, 그리고 모든 제품을 향한 정성에서 시작된다고 믿습니다.", second: "Hồng Tâm Rosic Global은 베트남의 산지 공급을 국내외 파트너의 수요와 연결합니다. 모든 협업은 요구사항을 정확히 이해하고, 투명하게 소통하며, 함께 장기적인 방향을 세우는 데서 시작합니다.", link: "협업 과정 살펴보기", values: [{ title: "산지에서부터", body: "원산지를 중요하게 봅니다." }, { title: "모든 제품에", body: "선별에 정성을 더합니다." }, { title: "모든 연결에", body: "장기적인 협업을 지향합니다." }] },
    catalog: { eyebrow: "베트남 산지에서", title: "계절마다 나누고 싶은 맛.", body: "농산물 라인업을 살펴보고 귀사의 요구에 맞는 제품을 찾아보세요.", filter: "제품군 필터", search: "제품 검색", detail: "상세 보기", viewProduct: (title) => `${title} 보기`, resultCount: (count) => `${count}개 제품`, noResultTitle: "조건에 맞는 제품이 없습니다", noResultBody: "검색어를 짧게 입력하거나 전체 카탈로그를 확인해 보세요.", reset: "모든 제품 보기", note: "소개용 카탈로그입니다. 계절, 포장 및 공급 가능 여부는 문의별로 확인됩니다." }, tabs: { all: "전체", fruit: "신선 과일", vegetables: "제철 채소", nuts: "견과류와 곡물", processed: "가공 농산물" },
    journey: { title: ["하나의 여정.", "모든 단계에 담은 정성."], lead: "산지 선정부터 납품까지, 모든 단계에는 상호 이해와 긴밀한 협업이 필요합니다.", label: "협업 과정", steps: [{ title: "산지에서 시작합니다", description: "원산지와 제철 시기를 이해한 뒤, 요구에 맞는 제품을 선택합니다.", alt: "햇빛을 받은 푸른 차밭", caption: "좋은 땅에서 이야기가 시작됩니다." }, { title: "제품을 세심하게 고릅니다", description: "각 주문에 중요한 품종, 숙도, 크기와 세부 조건을 함께 확인합니다.", alt: "밝은 배경에 놓인 과일, 캐슈넛과 커피", caption: "모든 요구에 맞는 신중한 선택." }, { title: "포장까지 세심하게 준비합니다", description: "농산물별로 전처리, 포장 규격과 보관 조건을 합의합니다.", alt: "밝은 공간의 농산물 선별 및 포장 라인", caption: "제품을 알아야 제대로 준비할 수 있습니다." }, { title: "목적지까지 연결합니다", description: "납품 일정, 수령지와 각자의 책임을 명확히 해 매끄러운 인계를 돕습니다.", alt: "창고와 화물 집하 공간", caption: "모든 과정에서 명확하게 협업합니다." }] },
    partners: { title: ["함께할 때,", "더 멀리 갑니다."], lead: "유통사, 리테일사, 수입 파트너를 비롯해 공동의 기준을 바탕으로 한 모든 연결을 소중히 여깁니다.", link: "협업 기회 논의하기", types: ["유통 파트너", "리테일 및 식품 서비스", "수입 파트너", "제조사"], qualityTitle: "처음부터 명확하게", qualityBody: "원산지, 규격, 품질 서류와 납품 조건은 모든 제품과 주문별로 함께 확인해야 합니다." },
    journal: { title: "풍요로운 계절에서 전하는 이야기.", lead: "제품, 산지, 그리고 실질적인 협업을 시작하는 방법에 관한 인사이트입니다.", read: "이야기 읽기", minutes: (count) => `${count}분 읽기`, articles: {
      "chon-nong-san-theo-mua": { title: "제철을 고르고, 제품을 이해하세요.", category: "제철 소싱", alt: "자연광 아래 펼쳐진 푸른 차밭", excerpt: "적합한 농산물 라인업은 사용 목적과 계절의 변화를 이해하는 데서 시작됩니다.", sections: [{ title: "제품이 도착할 곳부터 생각하세요", body: "리테일, 식품 서비스, 가공은 서로 다른 제품 조건을 필요로 합니다. 사용 목적, 필요 시점, 크기·숙도·외관 같은 우선 조건을 정리해 보세요." }, { title: "제철 시기와 대안을 논의하세요", body: "수확 시기와 공급 상황은 산지마다 달라질 수 있습니다. 계획할 때에는 공급 가능 기간, 예상 물량, 해당 시기에 적합하지 않을 때의 대안을 확인하세요." }, { title: "로트 정보를 확인하세요", body: "일반적인 제품명과 소개 이미지만으로는 모든 로트의 특성을 알 수 없습니다. 주문 전 제품 설명, 원산지, 포장 및 수령 검수 방식을 합의하고, 필요하면 샘플을 검토하세요." }] },
      "dong-goi-va-van-chuyen": { title: "좋은 여정은 알맞은 포장에서 시작됩니다.", category: "제품 관점", alt: "밝은 공간의 농산물 선별 및 포장 라인", excerpt: "포장과 납품 계획은 처음부터 제품과 함께 논의하는 것이 좋습니다.", sections: [{ title: "포장은 제품 특성에서 시작됩니다", body: "신선 과일, 잎채소, 건조 원료는 요구사항이 서로 다릅니다. 상자 크기만 고르기보다, 제품별 자재, 단위 중량, 적재 방식과 보관 조건을 함께 정하세요." }, { title: "전체 운송 경로를 살펴보세요", body: "상품 준비부터 사용까지의 시간은 포장 방식에 영향을 줍니다. 운송 수단, 인계 지점, 수령 일정과 목적지 보관 조건을 명확히 하세요." }, { title: "수령과 검수 방법을 합의하세요", body: "라벨, 포장 수량, 로트 정보는 대조를 더 쉽게 만듭니다. 납품 전에 수령 담당자, 검수 방식, 회신 시점, 이슈 발생 시 연락 창구를 정하세요." }] },
      "bat-dau-don-hang-b2b": { title: "첫 B2B 주문은 명확한 소통에서 시작됩니다.", category: "파트너 연결", alt: "과일, 캐슈넛과 커피가 함께 놓인 모습", excerpt: "간결하면서도 충분한 문의는 양쪽 팀이 실질적인 논의를 시작할 수 있게 합니다.", sections: [{ title: "필요한 내용을 알려 주세요", body: "제품, 사용 목적, 예상 물량부터 알려 주세요. 크기, 가공, 포장 조건이 있다면 적고, 아직 정해지지 않았다면 안내가 필요한 부분을 말씀해 주세요." }, { title: "일정과 목적지를 공유하세요", body: "필요 납기일, 수령지, 예상 구매 빈도는 현실적인 논의에 도움이 됩니다. 국제 주문이라면 목표 시장과 도착지에서 요구하는 서류를 알려 주세요." }, { title: "합의 내용을 확인하세요", body: "주문을 확정하기 전 제품, 수량, 가격, 규격, 납품 일정과 조건을 다시 확인하세요. 명확한 요약은 양쪽이 다음 단계를 준비하도록 돕습니다." }] },
    } },
    footer: { tagline: ["정성으로 키운 가치.", "오래 이어지는 파트너십."], explore: "둘러보기", products: "제품", invitation: "함께 이야기를 시작해 보세요.", greeting: "Hồng Tâm에 문의", social: "빠른 연결", privacy: "정보 및 개인정보", backTop: "맨 위로" },
    dialog: { close: "상세 닫기", articleCta: "더 알아보기", productGroup: "제품군", format: "제품 형태", formatValue: "요구사항에 맞춰 협의", imageNote: "제품 이미지는 참고용입니다. 원산지, 계절 및 사양은 로트별로 확인됩니다.", request: "이 제품 문의", policyTitle: "정보 및 개인정보", policyLead: "웹사이트 콘텐츠와 견적 문의 정보의 이용 방식입니다.", policySections: [{ title: "제품 정보", body: "카탈로그와 이미지는 제품군을 소개하기 위한 것입니다. 일부 연출 이미지는 AI로 제작되었으며, 특정 산지나 회사 소유 시설을 증명하지 않습니다. 원산지, 품질 서류, 사양 및 공급 가능 여부는 문의 과정에서 확인해야 합니다." }, { title: "견적 문의", body: "양식을 제출하면 정보가 견적 시스템으로 전송되어 영업팀 배정과 이메일 확인에 사용됩니다. WhatsApp 확인 메시지는 명시적으로 동의한 경우에만 전송하며, 동의하지 않으면 WhatsApp 메시지를 보내지 않습니다." }, { title: "참고 콘텐츠", body: "게시물은 상업적 논의를 위한 소개 및 안내 자료이며, 인증서나 경영 실적 자료가 아닙니다." }] },
  },
  ja: {
    skip: "本文へ移動", nav: { home: "ホーム", about: "私たちについて", journey: "取り組み", products: "商品", partners: "パートナー", journal: "インサイト", contact: "お問い合わせ" }, exportCatalog: "輸出カタログ", language: "言語を選択", openMenu: "メニューを開く", closeMenu: "メニューを閉じる", primaryNavigation: "メインナビゲーション", mobileMenuTitle: "ナビゲーション", productNavigation: "商品とお問い合わせ",
    brand: { topbar: "心を込めたものづくり、未来を見据えた取引", mobileDescription: "Hồng Tâm Rosic Global を見る", logoAlt: "Hồng Tâm Rosic Global のロゴ", homeLabel: "Hồng Tâm Rosic Global ホーム" },
    theme: { switchToDark: "ダークモードに切り替える", switchToLight: "ライトモードに切り替える", light: "ライト", dark: "ダーク" },
    hero: { eyebrow: "ベトナムから、世界のパートナーへ", start: "大地の恵み。", accent: "心を込めて届けます。", first: "ベトナムの良質な農産品を、世界のパートナーへつなぎます。", second: "一つひとつの収穫期を大切にし、長く続く協業を育てます。", cta: "輸出カタログを見る", origin: "ベトナムの農産品", caption: "価値を育て、信頼を築く。" }, marquee: ["生鮮果物", "旬の野菜", "ナッツと穀物", "加工農産品"], marqueeLabel: "農産品カテゴリー", marqueeHelp: "タップまたは Enter キーで動きを一時停止・再開できます。",
    about: { alt: "明るい背景に並んだマンゴー、レッドドラゴンフルーツ、メロン、アボカド、カシューナッツ、コーヒー", eyebrow: "HỒNG TÂM のストーリー", title: ["ベトナムに根を張り、", "世界を見据える。"], first: "農産品の価値は、土地、生産者、そして一つひとつの商品への誠実な姿勢から生まれると考えています。", second: "Hồng Tâm Rosic Global は、ベトナムの産地供給を国内外のパートナーのニーズへつなぎます。すべての協業は、要件を正しく理解し、率直に対話し、長期的な方向性を共有することから始まります。", link: "私たちの取り組みを見る", values: [{ title: "産地から", body: "原産地を大切にします。" }, { title: "一つひとつの商品へ", body: "丁寧に選びます。" }, { title: "すべてのつながりへ", body: "長く続く協業を目指します。" }] },
    catalog: { eyebrow: "ベトナムの産地から", title: "季節ごとに、分かち合いたい味わい。", body: "農産品のラインアップから、ご要望に合う商品をお探しください。", filter: "商品グループを絞り込む", search: "商品を検索", detail: "詳細を見る", viewProduct: (title) => `${title}を見る`, resultCount: (count) => `${count}件の商品`, noResultTitle: "該当する商品がありません", noResultBody: "短い検索語を試すか、全カタログをご覧ください。", reset: "すべての商品を見る", note: "紹介用カタログです。季節、梱包、供給可否はお問い合わせごとに確認します。" }, tabs: { all: "すべて", fruit: "生鮮果物", vegetables: "旬の野菜", nuts: "ナッツと穀物", processed: "加工農産品" },
    journey: { title: ["一つの道のり。", "すべての工程に心を込めて。"], lead: "産地の選定から納品まで、各段階で相互理解と密な連携を大切にしています。", label: "取り組みのステップ", steps: [{ title: "産地から始める", description: "原産地と旬を理解し、ご要望に合う商品を選びます。", alt: "陽光に照らされた緑の茶畑", caption: "良い土から、物語が始まります。" }, { title: "一つひとつ選ぶ", description: "品種、熟度、サイズ、注文ごとの重要な条件をすり合わせます。", alt: "明るい背景に並んだ果物、カシューナッツとコーヒー", caption: "一つひとつのご要望に、納得の選択を。" }, { title: "梱包まで丁寧に", description: "農産品ごとに、前処理、梱包仕様、保管条件を確認します。", alt: "明るい空間にある農産品の選別・包装ライン", caption: "商品を知ることが、適切な準備につながります。" }, { title: "目的地へつなぐ", description: "納品時期、受取場所、双方の役割を明確にし、円滑な引き渡しを支えます。", alt: "倉庫と貨物の集荷エリア", caption: "すべての段階で、明確に連携します。" }] },
    partners: { title: ["ともに進めば、", "もっと遠くへ。"], lead: "販売代理店、小売事業者、輸入パートナーなど、共通の基準を大切にするすべてのつながりを尊重します。", link: "協業の可能性を相談する", types: ["販売代理店", "小売・フードサービス", "輸入パートナー", "製造事業者"], qualityTitle: "最初から明確に", qualityBody: "原産地、仕様、品質書類、納品条件は、すべての商品と注文ごとに確認する必要があります。" },
    journal: { title: "豊かな季節からの便り。", lead: "商品、産地、そして実りある協業の始め方についての実践的な視点です。", read: "記事を読む", minutes: (count) => `${count}分で読めます`, articles: {
      "chon-nong-san-theo-mua": { title: "旬を選び、商品を理解する。", category: "季節の調達", alt: "自然光に照らされた緑の茶畑", excerpt: "適切な農産品のラインアップは、用途と季節の変化を理解することから始まります。", sections: [{ title: "商品が届く先から考える", body: "小売、フードサービス、加工では求められる条件が異なります。用途、必要な時期、サイズ、熟度、外観などの優先事項を整理しましょう。" }, { title: "旬と代替案を相談する", body: "収穫時期と供給状況は産地によって変わります。計画時には、供給可能な時期、予想数量、旬が合わない場合の代替案を確認してください。" }, { title: "ロットの情報を確認する", body: "一般的な商品名や紹介写真だけでは、すべてのロットの特徴は分かりません。注文前に商品説明、原産地、梱包、受入検査を合意し、必要に応じてサンプルを確認します。" }] },
      "dong-goi-va-van-chuyen": { title: "良い旅は、適切な梱包から始まる。", category: "商品について", alt: "明るい空間にある農産品の選別・包装ライン", excerpt: "梱包と納品計画は、最初から商品とあわせて話し合うべき要素です。", sections: [{ title: "梱包は商品の特性に合わせる", body: "果物、葉物野菜、乾燥原料では必要な条件が異なります。箱のサイズだけでなく、素材、単位重量、詰め方、商品の保管条件をすり合わせます。" }, { title: "輸送全体を見通す", body: "出荷準備から使用までの時間は梱包の判断に影響します。輸送方法、引継ぎ地点、受取予定、目的地での保管条件を明確にしましょう。" }, { title: "受取りと検査を合意する", body: "ラベル、梱包数、ロット情報があると照合しやすくなります。納品前に、受取担当者、検査方法、回答時期、確認事項がある場合の窓口を決めます。" }] },
      "bat-dau-don-hang-b2b": { title: "最初の B2B 注文は、明確な対話から。", category: "パートナー連携", alt: "果物、カシューナッツ、コーヒーを一緒に並べた様子", excerpt: "簡潔で必要な情報を備えたお問い合わせが、両チームの実務的な対話の出発点になります。", sections: [{ title: "必要なものを伝える", body: "商品、用途、想定数量からお知らせください。サイズ、加工、梱包の条件があれば明記し、未確定の場合は助言が必要な点をお伝えください。" }, { title: "時期と目的地を共有する", body: "必要な納期、受取場所、想定購入頻度は、現実的な対話に役立ちます。国際注文では、対象市場と到着地で必要な書類もお知らせください。" }, { title: "合意内容を確認する", body: "注文を確定する前に、商品、数量、価格、仕様、納品予定、条件を照合します。明確なまとめが、双方の次の準備を支えます。" }] },
    } },
    footer: { tagline: ["心を込めて育てる価値。", "長く続くパートナーシップ。"], explore: "見る", products: "商品", invitation: "まずはお話ししませんか。", greeting: "Hồng Tâm に相談", social: "クイックリンク", privacy: "情報とプライバシー", backTop: "ページ上部へ" },
    dialog: { close: "詳細を閉じる", articleCta: "さらに相談する", productGroup: "商品グループ", format: "商品形態", formatValue: "ご要望に合わせてご相談", imageNote: "商品画像はイメージです。原産地、旬、仕様はロットごとに確認されます。", request: "この商品を問い合わせる", policyTitle: "情報とプライバシー", policyLead: "ウェブサイトの内容と見積もりお問い合わせ情報の利用方法。", policySections: [{ title: "商品情報", body: "カタログと画像は商品グループを紹介するためのものです。一部のイメージ画像は AI により作成されており、特定の産地や自社所有施設を示すものではありません。原産地、品質書類、仕様、供給可否はお問い合わせ時に確認が必要です。" }, { title: "見積もりのお問い合わせ", body: "フォームを送信すると、情報は見積もりシステムへ送られ、営業担当への振り分けとメール確認に使用されます。WhatsApp での確認メッセージは、明示的に同意した場合にのみ送信します。同意がない場合、WhatsApp のメッセージは送信しません。" }, { title: "参考コンテンツ", body: "記事は商談のための紹介・案内情報であり、認証書や業績資料ではありません。" }] },
  },
  ar: {
    skip: "الانتقال إلى المحتوى الرئيسي", nav: { home: "الرئيسية", about: "من نحن", journey: "منهجنا", products: "المنتجات", partners: "الشركاء", journal: "رؤى", contact: "تواصل معنا" }, exportCatalog: "كتالوج التصدير", language: "اختر اللغة", openMenu: "فتح القائمة", closeMenu: "إغلاق القائمة", primaryNavigation: "التنقل الرئيسي", mobileMenuTitle: "التنقل", productNavigation: "المنتجات والتواصل",
    brand: { topbar: "نصنّع بقلب ونتاجر برؤية", mobileDescription: "اكتشف Hồng Tâm Rosic Global", logoAlt: "شعار Hồng Tâm Rosic Global", homeLabel: "الصفحة الرئيسية لـ Hồng Tâm Rosic Global" },
    theme: { switchToDark: "التبديل إلى الوضع الداكن", switchToLight: "التبديل إلى الوضع الفاتح", light: "فاتح", dark: "داكن" },
    hero: { eyebrow: "من فيتنام إلى شركاء العالم", start: "خيرات الأرض.", accent: "نقدمها بعناية.", first: "نصل أجود المنتجات الزراعية الفيتنامية بشركائنا حول العالم.", second: "نعتني بكل حصاد ونبني شراكات تدوم.", cta: "استكشف كتالوج التصدير", origin: "منتجات زراعية من فيتنام", caption: "ننمّي القيمة ونبني الثقة." }, marquee: ["فواكه طازجة", "خضروات موسمية", "مكسرات وحبوب", "منتجات زراعية مصنّعة"], marqueeLabel: "فئات المنتجات الزراعية", marqueeHelp: "المس أو اضغط Enter لإيقاف الشريط المتحرك أو استئنافه.",
    about: { alt: "مانجو وفاكهة التنين الحمراء والشمام والأفوكادو والكاجو والقهوة على خلفية فاتحة", eyebrow: "قصة HỒNG TÂM", title: ["جذور في فيتنام.", "ونظرة إلى العالم."], first: "نؤمن أن قيمة المنتجات الزراعية تبدأ بالعناية بالأرض والمزارعين وكل منتج.", second: "تربط Hồng Tâm Rosic Global إمدادات المناطق الزراعية في فيتنام باحتياجات الشركاء محلياً ودولياً. تبدأ كل شراكة بفهم واضح للمتطلبات وحوار صريح ورؤية مشتركة طويلة الأمد.", link: "اكتشف منهجنا", values: [{ title: "من المصدر", body: "نهتم بالمنشأ." }, { title: "إلى كل منتج", body: "ننتقي بعناية." }, { title: "في كل شراكة", body: "نبني لعلاقة طويلة الأمد." }] },
    catalog: { eyebrow: "من مناطق الزراعة في فيتنام", title: "في كل موسم ما يستحق أن يُشارك.", body: "تعرّف إلى مجموعتنا الزراعية واختر المنتج الأنسب لاحتياجك.", filter: "تصفية مجموعات المنتجات", search: "ابحث عن منتجات", detail: "عرض التفاصيل", viewProduct: (title) => `عرض ${title}`, resultCount: (count) => `${count} منتجات`, noResultTitle: "لم يتم العثور على منتج مطابق", noResultBody: "جرّب عبارة بحث أقصر أو اعرض الكتالوج كاملاً.", reset: "عرض كل المنتجات", note: "هذا كتالوج تعريفي. يتم تأكيد الموسم والتعبئة والتوافر لكل استفسار." }, tabs: { all: "الكل", fruit: "فواكه طازجة", vegetables: "خضروات موسمية", nuts: "مكسرات وحبوب", processed: "منتجات زراعية مصنّعة" },
    journey: { title: ["رحلة واحدة.", "عناية في كل خطوة."], lead: "من اختيار المصدر إلى التسليم، تحتاج كل مرحلة إلى فهم متبادل وتنسيق وثيق.", label: "خطوات منهجنا", steps: [{ title: "نبدأ من المصدر", description: "نفهم المنشأ والموسم قبل اختيار المنتج المناسب للطلب.", alt: "تلال شاي خضراء تحت ضوء الشمس", caption: "من الأرض الطيبة تبدأ الحكاية." }, { title: "نختار بعناية", description: "نتفق على الصنف ودرجة النضج والحجم والتفاصيل المهمة لكل طلب.", alt: "فواكه وكاجو وقهوة مرتبة على خلفية فاتحة", caption: "اختيار مدروس لكل احتياج." }, { title: "نعتني بالتعبئة", description: "نتفق على التجهيز والتعبئة وظروف الحفظ لكل منتج زراعي.", alt: "خط فرز وتعبئة للمنتجات الزراعية في مساحة مشرقة", caption: "معرفة المنتج هي بداية التحضير الصحيح." }, { title: "نصل إلى الوجهة", description: "نوضّح موعد التسليم والوجهة ومسؤوليات الأطراف لضمان انتقال سلس.", alt: "مستودع ومنطقة تجميع للبضائع", caption: "تنسيق واضح في كل مرحلة." }] },
    partners: { title: ["نصل أبعد،", "عندما نمضي معاً."], lead: "من الموزعين وتجار التجزئة إلى شركاء الاستيراد، نثمّن العلاقات التي تقوم على معايير مشتركة.", link: "ناقش فرصة شراكة", types: ["الموزعون", "التجزئة وخدمات الأغذية", "شركاء الاستيراد", "المصنّعون"], qualityTitle: "وضوح منذ البداية", qualityBody: "يجب مراجعة المنشأ والمواصفات ووثائق الجودة وشروط التسليم لكل منتج وكل طلب." },
    journal: { title: "رسائل من مواسم العطاء.", lead: "رؤى عملية حول المنتجات والمصادر وكيفية بدء شراكة مثمرة.", read: "اقرأ القصة", minutes: (count) => `${count} دقائق للقراءة`, articles: {
      "chon-nong-san-theo-mua": { title: "اختر الموسم المناسب وافهم المنتج.", category: "توريد موسمي", alt: "تلال شاي خضراء تحت ضوء طبيعي", excerpt: "تبدأ التشكيلة الزراعية المناسبة بفهم الاستخدام المقصود وطبيعة الموسم.", sections: [{ title: "ابدأ من وجهة المنتج", body: "للتجزئة وخدمات الأغذية والتصنيع احتياجات مختلفة. حدّد الاستخدام والوقت المطلوب والأولويات مثل الحجم أو النضج أو المظهر." }, { title: "ناقش الموسم والبدائل", body: "قد يختلف توقيت الحصاد والإمداد من منطقة زراعية إلى أخرى. عند التخطيط، اسأل عن فترة التوافر والكمية المتوقعة والبدائل المناسبة إذا لم يكن المنتج في موسمه." }, { title: "أكد معلومات الدفعة", body: "لا يصف الاسم العام والصورة التعريفية خصائص كل دفعة. قبل الطلب، اتفقا على وصف المنتج والمنشأ والتعبئة وفحوص الاستلام، وراجعا عينة عند الحاجة." }] },
      "dong-goi-va-van-chuyen": { title: "الرحلة الجيدة تبدأ بالتعبئة المناسبة.", category: "من منظور المنتج", alt: "خط فرز وتعبئة للمنتجات الزراعية في مساحة مشرقة", excerpt: "من الأفضل الاتفاق على التعبئة وخطة التسليم مع المنتج منذ البداية.", sections: [{ title: "التعبئة تتبع خصائص المنتج", body: "للفواكه والخضروات الورقية والمواد الجافة احتياجات مختلفة. بدلاً من اختيار حجم الصندوق فقط، اتفقوا على المادة والوزن لكل وحدة وطريقة الترتيب وظروف حفظ المنتج." }, { title: "انظر إلى مسار الرحلة كاملاً", body: "يؤثر الوقت من تجهيز البضاعة حتى استخدامها في قرار التعبئة. وضحوا وسيلة النقل ونقاط التسليم والجدول وظروف التخزين في الوجهة." }, { title: "اتفقوا على الاستلام والفحص", body: "تجعل الملصقات وعدد العبوات ومعلومات الدفعة المطابقة أسهل. اتفقوا مسبقاً على المستلم وطريقة الفحص وموعد الرد وجهة الاتصال عند الحاجة إلى توضيح." }] },
      "bat-dau-don-hang-b2b": { title: "أول طلب بين الشركات يبدأ بالوضوح.", category: "تواصل الشركاء", alt: "فواكه وكاجو وقهوة مرتبة معاً", excerpt: "يساعد طلب موجز ومكتمل الفريقين على بدء نقاش عملي حول الحاجة الفعلية.", sections: [{ title: "صف ما تحتاج إليه", body: "ابدأ بالمنتج والاستخدام والكمية المتوقعة. اذكر أي متطلبات للحجم أو المعالجة أو التعبئة، أو حدد الجوانب التي تريد مشورة بشأنها إن لم تكن محسومة." }, { title: "شارك الموعد والوجهة", body: "يساعد تاريخ الحاجة ومكان الاستلام وتواتر الشراء المتوقع على جعل النقاش عملياً. للطلبات الدولية، اذكر السوق المستهدف والوثائق المطلوبة في الوجهة." }, { title: "أكد ما تم الاتفاق عليه", body: "قبل تأكيد الطلب، راجعوا المنتج والكمية والسعر والمواصفات وجدول التسليم والشروط. يساعد الملخص الواضح كل طرف على الاستعداد للخطوة التالية." }] },
    } },
    footer: { tagline: ["قيمة تُنمّى بعناية.", "وشراكات تدوم."], explore: "استكشف", products: "المنتجات", invitation: "لنبدأ حواراً.", greeting: "تواصل مع Hồng Tâm", social: "روابط سريعة", privacy: "المعلومات والخصوصية", backTop: "العودة للأعلى" },
    dialog: { close: "إغلاق التفاصيل", articleCta: "تابع الحوار", productGroup: "مجموعة المنتجات", format: "شكل المنتج", formatValue: "يتم الاتفاق وفق احتياجكم", imageNote: "صورة المنتج للتوضيح. يتم تأكيد المنشأ والموسم والمواصفات لكل دفعة.", request: "استفسر عن هذا المنتج", policyTitle: "المعلومات والخصوصية", policyLead: "كيفية استخدام محتوى الموقع ومعلومات طلبات عرض السعر.", policySections: [{ title: "معلومات المنتج", body: "يُستخدم الكتالوج والصور للتعريف بفئات المنتجات. بعض الصور التوضيحية مُنشأة بالذكاء الاصطناعي ولا تثبت منطقة زراعية أو منشأة مملوكة للشركة. يجب تأكيد المنشأ ووثائق الجودة والمواصفات والتوافر عند الاستفسار." }, { title: "طلبات عرض السعر", body: "عند إرسال النموذج، تُرسل معلوماتك إلى نظام عروض الأسعار لتوجيهها إلى فريق المبيعات وإرسال تأكيد عبر البريد الإلكتروني. لا نستخدم رقم WhatsApp لإرسال رسالة تأكيد إلا عند موافقتك الصريحة؛ من دون الموافقة، لا نرسل رسالة عبر WhatsApp." }, { title: "محتوى مرجعي", body: "تقدم المقالات إرشادات تمهيدية للمحادثات التجارية، وليست شهادات أو بيانات عن أداء الأعمال." }] },
  },
  fr: {
    skip: "Aller au contenu principal", nav: { home: "Accueil", about: "À propos", journey: "Notre démarche", products: "Produits", partners: "Partenaires", journal: "Regards", contact: "Contact" }, exportCatalog: "Catalogue export", language: "Choisir la langue", openMenu: "Ouvrir le menu", closeMenu: "Fermer le menu", primaryNavigation: "Navigation principale", mobileMenuTitle: "Navigation", productNavigation: "Produits et contact",
    brand: { topbar: "Fabriquer avec cœur, commercer avec vision", mobileDescription: "Découvrir Hồng Tâm Rosic Global", logoAlt: "Logo Hồng Tâm Rosic Global", homeLabel: "Accueil Hồng Tâm Rosic Global" },
    theme: { switchToDark: "Passer au mode sombre", switchToLight: "Passer au mode clair", light: "Clair", dark: "Sombre" },
    hero: { eyebrow: "DU VIETNAM AUX PARTENAIRES DU MONDE", start: "L'essence de la terre.", accent: "Transmise avec attention.", first: "Nous relions les meilleurs produits agricoles vietnamiens aux partenaires du monde entier.", second: "Nous prenons soin de chaque récolte et construisons des partenariats durables.", cta: "Découvrir le catalogue export", origin: "Produits agricoles du Vietnam", caption: "Cultiver la valeur. Bâtir la confiance." }, marquee: ["Fruits frais", "Légumes de saison", "Noix et céréales", "Produits agricoles transformés"], marqueeLabel: "Catégories agricoles", marqueeHelp: "Touchez ou appuyez sur Entrée pour arrêter ou reprendre le défilement.",
    about: { alt: "Mangue, fruit du dragon rouge, melon, avocat, noix de cajou et café sur fond clair", eyebrow: "L'HISTOIRE DE HỒNG TÂM", title: ["Racinés au Vietnam.", "Tournés vers le monde."], first: "Nous pensons que la valeur agricole commence par l'attention portée à la terre, aux producteurs et à chaque produit.", second: "Hồng Tâm Rosic Global relie l'offre des régions agricoles vietnamiennes aux besoins de partenaires locaux et internationaux. Chaque partenariat commence par des besoins clairs, un dialogue ouvert et une direction partagée à long terme.", link: "Découvrir notre démarche", values: [{ title: "Dès l'origine", body: "L'origine compte." }, { title: "Dans chaque produit", body: "Une sélection attentive." }, { title: "Dans chaque relation", body: "Pensée pour durer." }] },
    catalog: { eyebrow: "DES RÉGIONS DE CULTURE DU VIETNAM", title: "À chaque saison, une saveur à partager.", body: "Parcourez notre sélection agricole et trouvez le produit adapté à votre besoin.", filter: "Filtrer les familles de produits", search: "Rechercher des produits", detail: "Voir les détails", viewProduct: (title) => `Voir ${title}`, resultCount: (count) => `${count} produits`, noResultTitle: "Aucun produit correspondant", noResultBody: "Essayez un terme plus court ou revenez au catalogue complet.", reset: "Voir tous les produits", note: "Ce catalogue est une présentation. Saisonnalité, conditionnement et disponibilité sont confirmés pour chaque demande." }, tabs: { all: "Tous", fruit: "Fruits frais", vegetables: "Légumes de saison", nuts: "Noix et céréales", processed: "Produits agricoles transformés" },
    journey: { title: ["Un même parcours.", "De l'attention à chaque étape."], lead: "Du choix de la source à la livraison, chaque étape demande compréhension mutuelle et coordination étroite.", label: "Étapes de notre démarche", steps: [{ title: "Commencer à la source", description: "Comprendre l'origine et la saisonnalité avant de choisir le produit adapté au besoin.", alt: "Collines de thé vert baignées de soleil", caption: "Toute histoire commence sur une bonne terre." }, { title: "Sélectionner avec discernement", description: "Aligner variété, maturité, calibre et détails importants pour chaque commande.", alt: "Fruits, noix de cajou et café sur fond clair", caption: "Un choix réfléchi pour chaque besoin." }, { title: "Soigner le conditionnement", description: "Définir préparation, emballage et conditions de conservation pour chaque produit agricole.", alt: "Ligne lumineuse de tri et de conditionnement des produits agricoles", caption: "Bien connaître le produit pour bien le préparer." }, { title: "Relier à la destination", description: "Clarifier calendrier, lieu de réception et responsabilités pour une remise fluide.", alt: "Entrepôt et zone de regroupement des marchandises", caption: "Une coordination claire à chaque étape." }] },
    partners: { title: ["Aller plus loin,", "ensemble."], lead: "Des distributeurs et détaillants aux partenaires importateurs, nous valorisons les relations fondées sur des exigences partagées.", link: "Échanger sur un partenariat", types: ["Distributeurs", "Distribution & restauration", "Partenaires importateurs", "Fabricants"], qualityTitle: "Clair dès le départ", qualityBody: "L'origine, les spécifications, les documents qualité et les conditions de livraison doivent être vérifiés pour chaque produit et chaque commande." },
    journal: { title: "Regards sur les saisons de culture.", lead: "Des perspectives concrètes sur les produits, l'approvisionnement et le démarrage d'un partenariat utile.", read: "Lire l'article", minutes: (count) => `${count} min de lecture`, articles: {
      "chon-nong-san-theo-mua": { title: "Choisir la bonne saison, comprendre le produit.", category: "Approvisionnement saisonnier", alt: "Collines de thé vert à la lumière naturelle", excerpt: "Une sélection agricole pertinente commence par la compréhension de l'usage et des réalités de la saison.", sections: [{ title: "Commencer par la destination", body: "La distribution, la restauration et la transformation ont des exigences différentes. Précisez l'usage, le délai souhaité et vos priorités telles que le calibre, la maturité ou la présentation." }, { title: "Échanger sur la saison et les alternatives", body: "La période de récolte et l'offre varient selon les régions. Lors de la planification, renseignez-vous sur la fenêtre de disponibilité, les volumes attendus et les alternatives adaptées." }, { title: "Confirmer les informations du lot", body: "Un nom générique et une photo de présentation ne décrivent pas chaque lot. Avant commande, convenez de la description produit, de l'origine, du conditionnement et des contrôles à réception; examinez un échantillon si nécessaire." }] },
      "dong-goi-va-van-chuyen": { title: "Un bon trajet commence par le bon emballage.", category: "Point de vue produit", alt: "Ligne lumineuse de tri et de conditionnement des produits agricoles", excerpt: "Le conditionnement et le plan de livraison gagnent à être définis avec le produit dès le départ.", sections: [{ title: "L'emballage suit le produit", body: "Les fruits frais, légumes-feuilles et matières sèches n'ont pas les mêmes besoins. Au-delà du format du carton, définissez matière, poids unitaire, disposition et conditions de conservation." }, { title: "Voir l'ensemble du parcours", body: "Le temps entre la préparation et l'utilisation influence le choix d'emballage. Clarifiez mode de transport, points de passage, réception et conditions de stockage à destination." }, { title: "Convenir de la réception et des contrôles", body: "Étiquettes, nombre de colis et informations de lot facilitent le rapprochement. Convenez en amont du destinataire, de la méthode de contrôle, du délai de réponse et du contact en cas de question." }] },
      "bat-dau-don-hang-b2b": { title: "Une première commande B2B commence par la clarté.", category: "Relation partenaire", alt: "Fruits, noix de cajou et café réunis", excerpt: "Une demande concise mais complète donne aux deux équipes un point de départ concret pour l'échange.", sections: [{ title: "Décrivez votre besoin", body: "Commencez par le produit, l'usage et le volume indicatif. Indiquez toute exigence de calibre, transformation ou conditionnement; si elle reste ouverte, précisez les points sur lesquels vous attendez un conseil." }, { title: "Partagez calendrier et destination", body: "La date souhaitée, le lieu de livraison et la fréquence d'achat estimée rendent l'échange plus concret. Pour une commande internationale, indiquez le marché cible et les documents requis à destination." }, { title: "Confirmez les éléments convenus", body: "Avant de confirmer une commande, rapprochez produit, quantité, prix, spécifications, calendrier et conditions. Une synthèse claire aide chaque partie à préparer la suite." }] },
    } },
    footer: { tagline: ["De la valeur cultivée avec soin.", "Des partenariats faits pour durer."], explore: "Découvrir", products: "Produits", invitation: "Commençons la conversation.", greeting: "Parler à Hồng Tâm", social: "Liens rapides", privacy: "Informations et confidentialité", backTop: "Haut de page" },
    dialog: { close: "Fermer les détails", articleCta: "Poursuivre l'échange", productGroup: "Famille de produits", format: "Format produit", formatValue: "À définir selon votre besoin", imageNote: "Image produit à titre illustratif. Origine, saisonnalité et spécifications sont confirmées pour chaque lot.", request: "Demander ce produit", policyTitle: "Informations et confidentialité", policyLead: "Comment sont utilisés les contenus du site et les informations transmises dans les demandes de devis.", policySections: [{ title: "Informations produit", body: "Le catalogue et les images présentent les familles de produits. Certaines images illustratives sont générées par IA et ne confirment ni une région de culture ni une installation appartenant à l'entreprise. Origine, documents qualité, spécifications et disponibilité doivent être confirmés lors de la demande." }, { title: "Demandes de devis", body: "Quand vous envoyez le formulaire, vos informations sont transmises au système de devis afin d'être orientées vers l'équipe commerciale et de vous adresser une confirmation par e-mail. Un message de confirmation WhatsApp n'est envoyé que si vous y consentez explicitement; sans consentement, aucun message WhatsApp n'est envoyé." }, { title: "Contenu de référence", body: "Les articles apportent une première orientation pour les échanges commerciaux; ils ne sont ni des certificats ni des communications de résultats." }] },
  },
  de: {
    skip: "Zum Hauptinhalt", nav: { home: "Startseite", about: "Über uns", journey: "Unser Vorgehen", products: "Produkte", partners: "Partner", journal: "Einblicke", contact: "Kontakt" }, exportCatalog: "Exportkatalog", language: "Sprache wählen", openMenu: "Menü öffnen", closeMenu: "Menü schließen", primaryNavigation: "Hauptnavigation", mobileMenuTitle: "Navigation", productNavigation: "Produkte und Kontakt",
    brand: { topbar: "Mit Herz hergestellt, mit Weitblick gehandelt", mobileDescription: "Hồng Tâm Rosic Global entdecken", logoAlt: "Logo von Hồng Tâm Rosic Global", homeLabel: "Hồng Tâm Rosic Global Startseite" },
    theme: { switchToDark: "Zum dunklen Design wechseln", switchToLight: "Zum hellen Design wechseln", light: "Hell", dark: "Dunkel" },
    hero: { eyebrow: "AUS VIETNAM ZU PARTNERN WELTWEIT", start: "Essenz der Erde.", accent: "Mit Sorgfalt geliefert.", first: "Wir verbinden hochwertige vietnamesische Agrarprodukte mit Partnern auf der ganzen Welt.", second: "Wir begleiten jede Ernte sorgfältig und bauen Partnerschaften auf, die Bestand haben.", cta: "Exportkatalog entdecken", origin: "Agrarprodukte aus Vietnam", caption: "Werte wachsen lassen. Vertrauen aufbauen." }, marquee: ["Frisches Obst", "Saisongemüse", "Nüsse & Getreide", "Verarbeitete Agrarprodukte"], marqueeLabel: "Agrarproduktgruppen", marqueeHelp: "Berühren Sie die Leiste oder drücken Sie Enter, um die Bewegung anzuhalten oder fortzusetzen.",
    about: { alt: "Mango, rote Drachenfrucht, Melone, Avocado, Cashewkerne und Kaffee vor hellem Hintergrund", eyebrow: "DIE GESCHICHTE VON HỒNG TÂM", title: ["In Vietnam verwurzelt.", "Global ausgerichtet."], first: "Wir sind überzeugt: Der Wert von Agrarprodukten beginnt mit Sorgfalt für den Boden, die Erzeuger und jedes einzelne Produkt.", second: "Hồng Tâm Rosic Global verbindet vietnamesische Anbaugebiete mit den Anforderungen lokaler und internationaler Partner. Jede Zusammenarbeit beginnt mit klaren Anforderungen, offenem Austausch und einer gemeinsamen langfristigen Perspektive.", link: "Unser Vorgehen entdecken", values: [{ title: "An der Quelle", body: "Herkunft zählt." }, { title: "In jedem Produkt", body: "Sorgfältig ausgewählt." }, { title: "In jeder Partnerschaft", body: "Auf Dauer angelegt." }] },
    catalog: { eyebrow: "AUS VIETNAMS ANBAUGEBIETEN", title: "Jede Saison bringt etwas, das man teilen möchte.", body: "Entdecken Sie unser Agrarangebot und finden Sie das passende Produkt für Ihren Bedarf.", filter: "Produktgruppen filtern", search: "Produkte suchen", detail: "Details ansehen", viewProduct: (title) => `${title} ansehen`, resultCount: (count) => `${count} Produkte`, noResultTitle: "Kein passendes Produkt gefunden", noResultBody: "Versuchen Sie einen kürzeren Suchbegriff oder öffnen Sie den Gesamtkatalog.", reset: "Alle Produkte ansehen", note: "Dieser Katalog dient der Vorstellung. Saison, Verpackung und Lieferfähigkeit werden für jede Anfrage bestätigt." }, tabs: { all: "Alle", fruit: "Frisches Obst", vegetables: "Saisongemüse", nuts: "Nüsse & Getreide", processed: "Verarbeitete Agrarprodukte" },
    journey: { title: ["Ein gemeinsamer Weg.", "Sorgfalt in jedem Schritt."], lead: "Von der Auswahl an der Quelle bis zur Lieferung braucht jede Etappe gegenseitiges Verständnis und enge Abstimmung.", label: "Schritte unseres Vorgehens", steps: [{ title: "An der Quelle beginnen", description: "Herkunft und Saison verstehen, bevor das passende Produkt ausgewählt wird.", alt: "Sonnenbeschienene grüne Teehügel", caption: "Auf gutem Boden beginnt jede Geschichte." }, { title: "Bewusst auswählen", description: "Sorte, Reife, Größe und die für jede Bestellung wichtigen Details abstimmen.", alt: "Obst, Cashewkerne und Kaffee vor hellem Hintergrund", caption: "Eine überlegte Wahl für jeden Bedarf." }, { title: "Sorgfältig verpacken", description: "Aufbereitung, Verpackung und Lagerbedingungen für jedes Agrarprodukt vereinbaren.", alt: "Helle Sortier- und Verpackungslinie für Agrarprodukte", caption: "Wer das Produkt kennt, bereitet es richtig vor." }, { title: "Mit dem Ziel verbinden", description: "Termin, Empfangsort und Verantwortlichkeiten klären, damit jede Übergabe reibungslos gelingt.", alt: "Lagerhalle und Bereich zur Warenbündelung", caption: "Klare Abstimmung auf jeder Etappe." }] },
    partners: { title: ["Gemeinsam", "weiter kommen."], lead: "Von Distributoren und Einzelhändlern bis zu Importpartnern schätzen wir Beziehungen, die auf gemeinsamen Maßstäben beruhen.", link: "Partnerschaft besprechen", types: ["Distributoren", "Einzelhandel & Foodservice", "Importpartner", "Hersteller"], qualityTitle: "Von Anfang an klar", qualityBody: "Herkunft, Spezifikation, Qualitätsunterlagen und Lieferbedingungen sollten für jedes Produkt und jeden Auftrag geprüft werden." },
    journal: { title: "Einblicke aus den Erntesaisons.", lead: "Praxisnahe Perspektiven zu Produkten, Beschaffung und dem Beginn einer erfolgreichen Zusammenarbeit.", read: "Artikel lesen", minutes: (count) => `${count} Min. Lesezeit`, articles: {
      "chon-nong-san-theo-mua": { title: "Die richtige Saison wählen, das Produkt verstehen.", category: "Saisonale Beschaffung", alt: "Grüne Teehügel im natürlichen Sonnenlicht", excerpt: "Ein passendes Agrarangebot beginnt mit dem Verständnis des Verwendungszwecks und der saisonalen Gegebenheiten.", sections: [{ title: "Beim Bestimmungsort beginnen", body: "Einzelhandel, Foodservice und Verarbeitung haben unterschiedliche Anforderungen. Klären Sie Zweck, gewünschten Zeitpunkt und Prioritäten wie Größe, Reife oder Erscheinungsbild." }, { title: "Saison und Alternativen besprechen", body: "Erntezeit und Verfügbarkeit können je Anbaugebiet variieren. Fragen Sie bei der Planung nach dem aktuellen Zeitfenster, erwarteten Mengen und passenden Alternativen." }, { title: "Informationen zur Charge bestätigen", body: "Ein allgemeiner Produktname und ein Einführungsbild beschreiben nicht jede Charge. Stimmen Sie vor der Bestellung Produktbeschreibung, Herkunft, Verpackung und Wareneingangsprüfung ab; prüfen Sie bei Bedarf ein Muster." }] },
      "dong-goi-va-van-chuyen": { title: "Eine gute Reise beginnt mit der passenden Verpackung.", category: "Produktperspektive", alt: "Helle Sortier- und Verpackungslinie für Agrarprodukte", excerpt: "Verpackung und Lieferplanung sollten von Anfang an gemeinsam mit dem Produkt abgestimmt werden.", sections: [{ title: "Die Verpackung folgt dem Produkt", body: "Frisches Obst, Blattgemüse und trockene Rohwaren haben unterschiedliche Anforderungen. Stimmen Sie neben der Kartongröße Material, Stückgewicht, Anordnung und Lagerbedingungen für das konkrete Produkt ab." }, { title: "Die gesamte Route betrachten", body: "Die Zeit zwischen Warenbereitstellung und Verwendung beeinflusst die Verpackungsentscheidung. Klären Sie Transportart, Übergabepunkte, Annahmeplan und Lagerbedingungen am Zielort." }, { title: "Annahme und Prüfung vereinbaren", body: "Etiketten, Packstückzahlen und Chargeninformationen erleichtern den Abgleich. Vereinbaren Sie vor der Lieferung Empfänger, Prüfverfahren, Rückmeldefrist und Kontaktstelle für Rückfragen." }] },
      "bat-dau-don-hang-b2b": { title: "Ein erster B2B-Auftrag beginnt mit Klarheit.", category: "Partnerverbindung", alt: "Zusammen arrangierte Früchte, Cashewkerne und Kaffee", excerpt: "Eine kurze, vollständige Anfrage gibt beiden Teams einen praktischen Ausgangspunkt für das Gespräch.", sections: [{ title: "Beschreiben Sie Ihren Bedarf", body: "Beginnen Sie mit Produkt, Verwendungszweck und Richtmenge. Nennen Sie Anforderungen an Größe, Verarbeitung oder Verpackung; falls etwas noch offen ist, benennen Sie den gewünschten Beratungsbedarf." }, { title: "Termin und Zielort teilen", body: "Benötigter Termin, Empfangsort und erwartete Kauffrequenz machen das Gespräch konkreter. Bei internationalen Aufträgen nennen Sie bitte den Zielmarkt und die am Bestimmungsort erforderlichen Unterlagen." }, { title: "Vereinbarte Punkte bestätigen", body: "Vor der Auftragsbestätigung sollten Produkt, Menge, Preis, Spezifikation, Lieferplan und Bedingungen abgeglichen werden. Eine klare Zusammenfassung hilft beiden Seiten bei der Vorbereitung des nächsten Schritts." }] },
    } },
    footer: { tagline: ["Mit Sorgfalt gewachsene Werte.", "Partnerschaften mit Bestand."], explore: "Entdecken", products: "Produkte", invitation: "Lassen Sie uns ins Gespräch kommen.", greeting: "Hồng Tâm kontaktieren", social: "Schnellzugriff", privacy: "Informationen & Datenschutz", backTop: "Nach oben" },
    dialog: { close: "Details schließen", articleCta: "Gespräch fortsetzen", productGroup: "Produktgruppe", format: "Produktform", formatValue: "Nach Ihrem Bedarf abstimmen", imageNote: "Produktbild zur Illustration. Herkunft, Saison und Spezifikationen werden je Charge bestätigt.", request: "Dieses Produkt anfragen", policyTitle: "Informationen & Datenschutz", policyLead: "Wie Website-Inhalte und die Angaben in Angebotsanfragen verwendet werden.", policySections: [{ title: "Produktinformationen", body: "Katalog und Bilder stellen Produktgruppen vor. Einige illustrative Bilder wurden mit KI erstellt und belegen weder ein Anbaugebiet noch eine dem Unternehmen gehörende Anlage. Herkunft, Qualitätsunterlagen, Spezifikationen und Verfügbarkeit müssen bei der Anfrage bestätigt werden." }, { title: "Angebotsanfragen", body: "Wenn Sie das Formular absenden, werden Ihre Angaben an das Angebotssystem übermittelt, dem Vertrieb zugeordnet und per E-Mail bestätigt. Eine WhatsApp-Bestätigung wird nur versendet, wenn Sie ausdrücklich zustimmen; ohne Zustimmung wird keine WhatsApp-Nachricht gesendet." }, { title: "Referenzinhalte", body: "Die Artikel bieten eine erste Orientierung für Geschäftsgespräche; sie sind keine Zertifikate oder Angaben zur Unternehmensleistung." }] },
  },
};

export function siteCopyFor(language) {
  return SITE_UI_COPY[language] ?? SITE_UI_COPY.en;
}

export function localizeJourneyItem(item, index, language) {
  const translation = SITE_UI_COPY[language]?.journey.steps[index];
  return translation ? { ...item, ...translation } : item;
}

export function localizeArticle(item, language) {
  const translation = SITE_UI_COPY[language]?.journal.articles[item.id];
  return translation ? { ...item, ...translation } : item;
}
